/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import com.formdev.flatlaf.FlatDarculaLaf;
import dao.PlataformaDao;
import entities.Medico;
import entities.Paciente;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author enzo.gpelizaro
 */
public class Login extends javax.swing.JFrame {
    PlataformaDao bd;

    /**
     * Creates new form loginPaciente
     */
    public Login() {
        initComponents();
        panelLoginMedico.setVisible(false);
        panelLoginPaciente.setVisible(true);
        bd = new PlataformaDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogin = new javax.swing.JLabel();
        btnPaciente = new javax.swing.JButton();
        btnMedico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelLoginMedico = new javax.swing.JPanel();
        jLabelCRM = new javax.swing.JLabel();
        jLabelSenhaM = new javax.swing.JLabel();
        txtLoginMedico = new javax.swing.JTextField();
        btnLoginMedico = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblCadastroMedico = new javax.swing.JLabel();
        pswSenhaMedico = new javax.swing.JPasswordField();
        panelLoginPaciente = new javax.swing.JPanel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelSenhaP = new javax.swing.JLabel();
        txtLoginPaciente = new javax.swing.JTextField();
        btnLoginPaciente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblCadastroPaciente = new javax.swing.JLabel();
        pswSenhaPaciente = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelLogin.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogin.setText("MedOn");
        jLabelLogin.setToolTipText("");
        getContentPane().add(jLabelLogin);
        jLabelLogin.setBounds(6, 6, 454, 38);

        btnPaciente.setText("Paciente");
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaciente);
        btnPaciente.setBounds(88, 90, 101, 30);

        btnMedico.setText("Médico");
        btnMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedico);
        btnMedico.setBounds(283, 90, 99, 30);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(214, 50, 42, 22);

        panelLoginMedico.setBackground(new java.awt.Color(204, 255, 255));
        panelLoginMedico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCRM.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCRM.setText("CRM:");
        panelLoginMedico.add(jLabelCRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 20));

        jLabelSenhaM.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSenhaM.setText("Senha:");
        panelLoginMedico.add(jLabelSenhaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        panelLoginMedico.add(txtLoginMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 370, 30));

        btnLoginMedico.setText("entrar");
        btnLoginMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginMedicoActionPerformed(evt);
            }
        });
        btnLoginMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginMedicoKeyPressed(evt);
            }
        });
        panelLoginMedico.add(btnLoginMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ainda não tem uma conta?");
        panelLoginMedico.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lblCadastroMedico.setForeground(new java.awt.Color(0, 0, 204));
        lblCadastroMedico.setText("Clique aqui para se registrar.");
        lblCadastroMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastroMedicoMouseClicked(evt);
            }
        });
        panelLoginMedico.add(lblCadastroMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));
        panelLoginMedico.add(pswSenhaMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 370, 30));

        getContentPane().add(panelLoginMedico);
        panelLoginMedico.setBounds(20, 190, 440, 290);

        panelLoginPaciente.setBackground(new java.awt.Color(204, 204, 255));
        panelLoginPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCPF.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCPF.setText("CPF:");
        panelLoginPaciente.add(jLabelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 20));

        jLabelSenhaP.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSenhaP.setText("Senha:");
        panelLoginPaciente.add(jLabelSenhaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        panelLoginPaciente.add(txtLoginPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 370, 30));

        btnLoginPaciente.setText("entrar");
        btnLoginPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPacienteActionPerformed(evt);
            }
        });
        btnLoginPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginPacienteKeyPressed(evt);
            }
        });
        panelLoginPaciente.add(btnLoginPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ainda não tem uma conta?");
        panelLoginPaciente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lblCadastroPaciente.setForeground(new java.awt.Color(0, 0, 204));
        lblCadastroPaciente.setText("Clique aqui para se registrar.");
        lblCadastroPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastroPacienteMouseClicked(evt);
            }
        });
        panelLoginPaciente.add(lblCadastroPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));
        panelLoginPaciente.add(pswSenhaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 370, 30));

        getContentPane().add(panelLoginPaciente);
        panelLoginPaciente.setBounds(20, 190, 440, 290);

        setSize(new java.awt.Dimension(496, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        panelLoginMedico.setVisible(false);
        panelLoginPaciente.setVisible(true);
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicoActionPerformed
        panelLoginPaciente.setVisible(false);
        panelLoginMedico.setVisible(true);
    }//GEN-LAST:event_btnMedicoActionPerformed

    private void btnLoginMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginMedicoActionPerformed
        String crm, senha;
        crm = txtLoginMedico.getText();
        senha = pswSenhaMedico.getText();
        Medico medico = new Medico(crm, senha);
        try{
            ResultSet login = bd.loginMedico(medico);
            if(login.next()){
                dispose();
                new MenuMedico(crm, senha).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Usuarios e senha inválidos");
            }

        } catch (ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null,"Entre em contato com o administrador e informe o erro:" + ex.getMessage() );
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Entre em contato com o administrador e informe o erro:" + ex.getMessage() );
        }
    }//GEN-LAST:event_btnLoginMedicoActionPerformed

    private void lblCadastroMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroMedicoMouseClicked
        new CadastroM().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCadastroMedicoMouseClicked

    private void btnLoginPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPacienteActionPerformed
        String cpf, s;
        cpf = txtLoginPaciente.getText();
        s = pswSenhaPaciente.getText();
        Paciente paciente = new Paciente(cpf, s);
        try{
            ResultSet login = bd.loginPaciente(paciente);
            if(login.next()){
                dispose();
                new MenuPaciente(cpf, s).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Usuarios e senha inválidos");
            }

        } catch (ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null,"Entre em contato com o administrador e informe o erro:" + ex.getMessage() );
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Entre em contato com o administrador e informe o erro:" + ex.getMessage() );
        }
    }//GEN-LAST:event_btnLoginPacienteActionPerformed

    private void lblCadastroPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroPacienteMouseClicked
        new CadastroP().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCadastroPacienteMouseClicked

    private void btnLoginMedicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginMedicoKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            btnLoginMedico.doClick();
        }
    }//GEN-LAST:event_btnLoginMedicoKeyPressed

    private void btnLoginPacienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginPacienteKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            btnLoginPaciente.doClick();
        }
    }//GEN-LAST:event_btnLoginPacienteKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel( new FlatDarculaLaf() );
                    break;
                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginMedico;
    private javax.swing.JButton btnLoginPaciente;
    private javax.swing.JButton btnMedico;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCRM;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelSenhaM;
    private javax.swing.JLabel jLabelSenhaP;
    private javax.swing.JLabel lblCadastroMedico;
    private javax.swing.JLabel lblCadastroPaciente;
    private javax.swing.JPanel panelLoginMedico;
    private javax.swing.JPanel panelLoginPaciente;
    private javax.swing.JPasswordField pswSenhaMedico;
    private javax.swing.JPasswordField pswSenhaPaciente;
    private javax.swing.JTextField txtLoginMedico;
    private javax.swing.JTextField txtLoginPaciente;
    // End of variables declaration//GEN-END:variables
}
