
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author enzo.gpelizaro
 */
public class CadastrarDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarDepartamento
     */
    public CadastrarDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfone = new javax.swing.JTextField();
        btnsalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de Departamentos");
        setForeground(java.awt.Color.orange);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 150, 220, 60);

        txtid.setBackground(new java.awt.Color(255, 51, 255));
        getContentPane().add(txtid);
        txtid.setBounds(300, 160, 310, 40);

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("NOME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 230, 220, 60);

        txtnome.setBackground(new java.awt.Color(255, 51, 255));
        getContentPane().add(txtnome);
        txtnome.setBounds(300, 240, 310, 40);

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("FONE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 310, 220, 60);

        txtfone.setBackground(new java.awt.Color(255, 51, 255));
        getContentPane().add(txtfone);
        txtfone.setBounds(300, 320, 310, 40);

        btnsalvar.setBackground(new java.awt.Color(0, 255, 51));
        btnsalvar.setText("SALVAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvar);
        btnsalvar.setBounds(630, 150, 250, 210);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meme-world-origins-o-comeco-do-fim-e-o-fim-do-comeco-19649483-170620202017.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, -40, 1260, 590);

        setSize(new java.awt.Dimension(1160, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        String id, n, f;
        id = txtid.getText();
        n = txtnome.getText();
        f = txtfone.getText();
        try {
            // conectar ao banco de dados empresa
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa","root","");
            // enviar os dados para a tabela do BD
            PreparedStatement st = conectar.prepareStatement("INSERT INTO departamentos VALUES(?, ?, ?)");
            st.setString(1, id);
            st.setString(2, n);
            st.setString(3, f);
            st.executeUpdate(); //executa o comando INSERT
            //exibir mnsg ao usuário:
            JOptionPane.showMessageDialog(null, "Departamento cadastrado");
            //limpar os campos
            txtid.setText("");
            txtnome.setText("");
            txtfone.setText(""); 
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Drive JDBC não encontrado na biblioteca |\n|Entre em contato com o suporte e informe o erro: "+ ex.getMessage());
        } catch (SQLException ex) {
            String erro = ex.getMessage();
            if (erro.contains("Duplicate entry")){
                JOptionPane.showMessageDialog(null, "Usuário já cadastrado");
            } else {
                            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: "+ ex.getMessage());

            }
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: "+ ex.getMessage());
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtfone;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
