
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection; // conectar com BD
import java.sql.DriverManager; // informar nome do BD, usuário e senha.
import java.sql.PreparedStatement; // executa o SQL Insert, comando que insere os dados na tabela
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author enzo.gpelizaro
 */
public class CadastrarUsuários extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarUsuários
     */
    public CadastrarUsuários() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmBoxCargo = new javax.swing.JComboBox<>();
        txtUser = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        cmBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Administrador", "Estagiário", "Vendedor" }));
        cmBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmBoxCargoActionPerformed(evt);
            }
        });
        getContentPane().add(cmBoxCargo);
        cmBoxCargo.setBounds(170, 210, 240, 50);
        getContentPane().add(txtUser);
        txtUser.setBounds(170, 50, 240, 50);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(170, 130, 240, 50);

        jLabel1.setText("Usuário");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 140, 50);

        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 130, 150, 50);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 280, 240, 50);

        setSize(new java.awt.Dimension(505, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // aqui
        String u, s, c;
        u = txtUser.getText();
        s = txtSenha.getText();
        c = cmBoxCargo.getSelectedItem().toString();
        try {
            // conectar ao banco de dados empresa
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa","root","");
            // enviar os dados para a tabela do BD
            PreparedStatement st = conectar.prepareStatement("INSERT INTO usuários VALUES(?, ?, ?)");
            st.setString(1, u);
            st.setString(2, s);
            st.setString(3, c);
            st.executeUpdate(); //executa o comando INSERT
            //exibir mnsg ao usuário:
            JOptionPane.showMessageDialog(null, "Usuário cadastrado");
            //limpar os campos
            txtUser.setText("");
            txtSenha.setText("");
            txtUser.requestFocus(); 
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Drive JDBC não encontrado na biblioteca |\n|Entre em contato com o suporte e informe o erro: "+ ex.getMessage());
        } catch (SQLException ex) {
            String erro = ex.getMessage();
            if (erro.contains("Duplicate entry")){
                JOptionPane.showMessageDialog(null, "Usuário já cadastrado");
            } else {
                            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: "+ ex.getMessage());

            }
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: "+ ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmBoxCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuários.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUsuários().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmBoxCargo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
