package telas;


import dao.EmpresaDao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author guilherme.msoares7
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    public Menu(String cargo) {
        initComponents();
        if (cargo.equalsIgnoreCase("Administrador")) {

        } else if (cargo.equalsIgnoreCase("Consultor")) {
            mnuUsuarios.setVisible(false);
            mnuFuncionarios.setVisible(false);
        } else if (cargo.equalsIgnoreCase("Estágiario")) {
            mnuUsuarios.setVisible(false);
            mnuFuncionarios.setVisible(false);
            itmCadastrarDepartamentos.setEnabled(false);
            itmExcluirDepartamentos.setEnabled(false);
            itmAlterarDepartamentos.setEnabled(false);
        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuDepartamentos = new javax.swing.JMenu();
        itmCadastrarDepartamentos = new javax.swing.JMenuItem();
        itmConsultarDepartamentos = new javax.swing.JMenuItem();
        itmExcluirDepartamentos = new javax.swing.JMenuItem();
        itmAlterarDepartamentos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmListarDepartamentos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itmBuscarDepartamentos = new javax.swing.JMenuItem();
        mnuFuncionarios = new javax.swing.JMenu();
        itmCadastrarFuncionarios = new javax.swing.JMenuItem();
        itmExcluirFuncionarios = new javax.swing.JMenuItem();
        itmAlterarFuncionarios = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itmListarFuncionarios = new javax.swing.JMenuItem();
        itmBuscarFuncionarios = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        itmCadastrarUsuarios = new javax.swing.JMenuItem();
        itmExcluirUsuarios = new javax.swing.JMenuItem();
        itmAlterarUsuarios = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itmListarUsuarios = new javax.swing.JMenuItem();
        itmBuscarUsuarios = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        itmInstrucoesAjuda = new javax.swing.JMenuItem();
        itmSobreAjuda = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Sistemas");
        getContentPane().setLayout(null);

        mnuDepartamentos.setText("Departamentos");

        itmCadastrarDepartamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadastrarDepartamentos.setText("Cadastrar");
        itmCadastrarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmCadastrarDepartamentos);

        itmConsultarDepartamentos.setText("Consultar");
        itmConsultarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultarDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmConsultarDepartamentos);

        itmExcluirDepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/excluir.png"))); // NOI18N
        itmExcluirDepartamentos.setText("Excluir");
        itmExcluirDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmExcluirDepartamentos);

        itmAlterarDepartamentos.setText("Alterar");
        itmAlterarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmAlterarDepartamentos);
        mnuDepartamentos.add(jSeparator1);

        itmListarDepartamentos.setText("Listar");
        itmListarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmListarDepartamentos);
        mnuDepartamentos.add(jSeparator2);

        itmBuscarDepartamentos.setText("Buscar");
        mnuDepartamentos.add(itmBuscarDepartamentos);

        jMenuBar1.add(mnuDepartamentos);

        mnuFuncionarios.setText("Funcionários");

        itmCadastrarFuncionarios.setText("Cadastrar");
        mnuFuncionarios.add(itmCadastrarFuncionarios);

        itmExcluirFuncionarios.setText("Excluir");
        mnuFuncionarios.add(itmExcluirFuncionarios);

        itmAlterarFuncionarios.setText("Alterar");
        itmAlterarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarFuncionariosActionPerformed(evt);
            }
        });
        mnuFuncionarios.add(itmAlterarFuncionarios);
        mnuFuncionarios.add(jSeparator4);

        itmListarFuncionarios.setText("Listar");
        mnuFuncionarios.add(itmListarFuncionarios);

        itmBuscarFuncionarios.setText("Buscar");
        mnuFuncionarios.add(itmBuscarFuncionarios);

        jMenuBar1.add(mnuFuncionarios);

        mnuUsuarios.setText("Usuários");

        itmCadastrarUsuarios.setText("Cadastrar");
        itmCadastrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmCadastrarUsuarios);

        itmExcluirUsuarios.setText("Excluir");
        itmExcluirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmExcluirUsuarios);

        itmAlterarUsuarios.setText("Alterar");
        itmAlterarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmAlterarUsuarios);
        mnuUsuarios.add(jSeparator3);

        itmListarUsuarios.setText("Listar");
        itmListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmListarUsuarios);

        itmBuscarUsuarios.setText("Buscar");
        itmBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmBuscarUsuarios);

        jMenuBar1.add(mnuUsuarios);

        mnuAjuda.setText("Ajuda");

        itmInstrucoesAjuda.setText("Instruções de uso");
        mnuAjuda.add(itmInstrucoesAjuda);

        itmSobreAjuda.setText("Sobre");
        mnuAjuda.add(itmSobreAjuda);

        jMenuBar1.add(mnuAjuda);

        mnuSair.setText("Sair");
        jMenuBar1.add(mnuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(688, 422));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmConsultarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsultarDepartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmConsultarDepartamentosActionPerformed

    private void itmCadastrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarUsuariosActionPerformed
        new CadastrarUsuarios().setVisible(true);
    }//GEN-LAST:event_itmCadastrarUsuariosActionPerformed

    private void itmExcluirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirUsuariosActionPerformed
        //pedir o usuario que vai excluir
        String u;
        u = JOptionPane.showInputDialog("Usuário: ");
        //conectar ao banco de dados
        try {
            int retorno = new EmpresaDao().excluirUsuario(u);
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso");

            } else {
                JOptionPane.showMessageDialog(null, "Usuário não encontrado");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_itmExcluirUsuariosActionPerformed

    private void itmCadastrarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarDepartamentosActionPerformed
        new CadastroDepartamento().setVisible(true);
    }//GEN-LAST:event_itmCadastrarDepartamentosActionPerformed

    private void itmExcluirDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirDepartamentosActionPerformed
        //pedir o usuario que vai excluir
        String id;
        id = JOptionPane.showInputDialog("ID do Departamento: ");
        //conectar ao banco de dados
        try {
            //Conectar ao banco de dados empresa
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresagui", "root", "");
            //3 - enviar os dados para a tabela BD 
            PreparedStatement st = conectar.prepareStatement("DELETE FROM departamento WHERE  ID = ?");
            st.setString(1, id);
            int retorno = st.executeUpdate(); // variavel para guardar o retorno do delete, se foi deletado ou não
            //4- exibir uma mensagem para o usuario
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Departamento excluído com sucesso");

            } else {
                JOptionPane.showMessageDialog(null, "Departamento não encontrado");
            }
            // 5 - limpar os campos
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmExcluirDepartamentosActionPerformed

    private void itmListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarUsuariosActionPerformed
        new ListarUsuarios().setVisible(true);
    }//GEN-LAST:event_itmListarUsuariosActionPerformed

    private void itmAlterarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarUsuariosActionPerformed
        // 1 - obter o nome do usuario que vai alterar
        String u;
        u = JOptionPane.showInputDialog("Usuário a alterar");
        try {
            // 2- Conectar ao banco de dados empresa
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresagui", "root", "");
            //3 - BUSCAR O USUARIO NO BC    
            PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios WHERE usuario = ?");
            st.setString(1, u);
            ResultSet usuario = st.executeQuery(); //COMANDO EXECUTANDO O SELECT    
            //4- VERIFICAR SE ENCONTROU USUARIO
            if (usuario.next()) { //NEXT É "SE ENCONTROU"
                // 5 - ENVIAR OS DADOS DO USUARIO PARA A TELA AlterarUsuarios
                String usu, sen, car;
                usu = usuario.getString("usuario");
                sen = usuario.getString("senha");
                car = usuario.getString("cargo");
                new AlterarUsuarios(usu, sen, car).setVisible(true);

            } else { // NÃO ENCONTROU
                JOptionPane.showMessageDialog(null, "Usuário não encontrado");
            }
            // 5 - limpar os campos
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarUsuariosActionPerformed

    private void itmBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarUsuariosActionPerformed
        String u;
        u = JOptionPane.showInputDialog("Usuário a Buscar");
        try {
            // 2- Conectar ao banco de dados empresa
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresagui", "root", "");
            //3 - BUSCAR O USUARIO NO BC    
            PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios WHERE usuario = ?");
            st.setString(1, u);
            ResultSet usuario = st.executeQuery(); //COMANDO EXECUTANDO O SELECT    
            //4- VERIFICAR SE ENCONTROU USUARIO
            if (usuario.next()) { //NEXT É "SE ENCONTROU"
                String usu, sen, car;
                usu = usuario.getString("usuario");
                sen = usuario.getString("senha");
                car = usuario.getString("cargo");
                JOptionPane.showMessageDialog(null, "Nome do Usuário: " + usu + "\n Senha do Usuário: " + sen + "\nCargo do Usuário: " + car);

            } else { // NÃO ENCONTROU
                JOptionPane.showMessageDialog(null, "Usuário não encontrado");
            }
            // 5 - limpar os campos
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmBuscarUsuariosActionPerformed

    private void itmAlterarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarDepartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAlterarDepartamentosActionPerformed

    private void itmAlterarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAlterarFuncionariosActionPerformed

    private void itmListarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarDepartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmListarDepartamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarDepartamentos;
    private javax.swing.JMenuItem itmAlterarFuncionarios;
    private javax.swing.JMenuItem itmAlterarUsuarios;
    private javax.swing.JMenuItem itmBuscarDepartamentos;
    private javax.swing.JMenuItem itmBuscarFuncionarios;
    private javax.swing.JMenuItem itmBuscarUsuarios;
    private javax.swing.JMenuItem itmCadastrarDepartamentos;
    private javax.swing.JMenuItem itmCadastrarFuncionarios;
    private javax.swing.JMenuItem itmCadastrarUsuarios;
    private javax.swing.JMenuItem itmConsultarDepartamentos;
    private javax.swing.JMenuItem itmExcluirDepartamentos;
    private javax.swing.JMenuItem itmExcluirFuncionarios;
    private javax.swing.JMenuItem itmExcluirUsuarios;
    private javax.swing.JMenuItem itmInstrucoesAjuda;
    private javax.swing.JMenuItem itmListarDepartamentos;
    private javax.swing.JMenuItem itmListarFuncionarios;
    private javax.swing.JMenuItem itmListarUsuarios;
    private javax.swing.JMenuItem itmSobreAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuDepartamentos;
    private javax.swing.JMenu mnuFuncionarios;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
