
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author EEEenxxeee
 */
public class CadastrarDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarDepartamento
     */
    public CadastrarDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNomeDepartamento = new javax.swing.JLabel();
        labelTelefoneDepartamento = new javax.swing.JLabel();
        labelIdDepartamento = new javax.swing.JLabel();
        textNomeDepartamento = new javax.swing.JTextField();
        textTelefoneDepartamento = new javax.swing.JTextField();
        textIdDepartamento = new javax.swing.JTextField();
        buttonSalvarDepartamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labelNomeDepartamento.setText("Nome:");
        getContentPane().add(labelNomeDepartamento);
        labelNomeDepartamento.setBounds(30, 100, 110, 40);

        labelTelefoneDepartamento.setText("Telefone:");
        getContentPane().add(labelTelefoneDepartamento);
        labelTelefoneDepartamento.setBounds(30, 170, 110, 40);

        labelIdDepartamento.setText("ID do departamento:");
        getContentPane().add(labelIdDepartamento);
        labelIdDepartamento.setBounds(30, 30, 110, 40);
        getContentPane().add(textNomeDepartamento);
        textNomeDepartamento.setBounds(160, 100, 200, 40);
        getContentPane().add(textTelefoneDepartamento);
        textTelefoneDepartamento.setBounds(160, 170, 200, 40);
        getContentPane().add(textIdDepartamento);
        textIdDepartamento.setBounds(160, 30, 200, 40);

        buttonSalvarDepartamento.setText("Salvar");
        buttonSalvarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSalvarDepartamento);
        buttonSalvarDepartamento.setBounds(210, 230, 100, 40);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalvarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarDepartamentoActionPerformed
        String id, n, t;
        id = textIdDepartamento.getText();
        int idDep = Integer.parseInt(id);
        n = textNomeDepartamento.getText();
        t = textTelefoneDepartamento.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/bdSistemaTeste1", "root", "p@$$w0rd");
            
            PreparedStatement st = c.prepareStatement("INSERT INTO departamento VALUES (?,?,?)");
            st.setInt(1,idDep);
            st.setString(2, n);
            st.setString(3, t);
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Departamento cadastrado");
            textIdDepartamento.setText("");
            textNomeDepartamento.setText("");
            textTelefoneDepartamento.setText("");
            textIdDepartamento.requestFocus();

            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CadastrarDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarDepartamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonSalvarDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSalvarDepartamento;
    private javax.swing.JLabel labelIdDepartamento;
    private javax.swing.JLabel labelNomeDepartamento;
    private javax.swing.JLabel labelTelefoneDepartamento;
    private javax.swing.JTextField textIdDepartamento;
    private javax.swing.JTextField textNomeDepartamento;
    private javax.swing.JTextField textTelefoneDepartamento;
    // End of variables declaration//GEN-END:variables
}
