
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection; //conectar com o bd
import java.sql.DriverManager; //informar o caminho, nome do bd, usuario e senha
import java.sql.PreparedStatement; //executar os comandos SQL
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author enzog
 */
public class CadastrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarUsuario
     */
    public CadastrarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCargo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        textSenha = new javax.swing.JTextField();
        textUsuario = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        buttonSalvar = new javax.swing.JButton();
        comboBoxCargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CadastroDeUsuarios");
        getContentPane().setLayout(null);

        labelCargo.setText("Cargo:");
        getContentPane().add(labelCargo);
        labelCargo.setBounds(30, 170, 120, 50);

        labelUsuario.setText("Usuário:");
        getContentPane().add(labelUsuario);
        labelUsuario.setBounds(30, 30, 120, 50);
        getContentPane().add(textSenha);
        textSenha.setBounds(150, 110, 210, 30);

        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(textUsuario);
        textUsuario.setBounds(150, 40, 210, 30);

        labelSenha.setText("Senha:");
        getContentPane().add(labelSenha);
        labelSenha.setBounds(30, 100, 120, 50);

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSalvar);
        buttonSalvar.setBounds(200, 240, 100, 27);

        comboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Gerente", "Estagiário", "Vendedor" }));
        getContentPane().add(comboBoxCargo);
        comboBoxCargo.setBounds(150, 180, 210, 30);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        // 1- pegar os dados digitados nos campos e guardar em variáveis
        String u, s, c;
        u = textUsuario.getText();
        s = textSenha.getText();
        c = comboBoxCargo.getSelectedItem().toString();
        
        try {
            // 2- conectar ao banco de dados bdSistemaTeste1 (linha única: Class.forName();)
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/bdSistemaTeste1", "root", "p@$$w0rd");
            
            //3- enviar dados para o bd selecionado
            PreparedStatement st = conectar.prepareStatement("INSERT INTO usuario VALUES (?,?,?)");
            st.setString(1,u);
            st.setString(2,s);
            st.setString(3,c);
            st.executeUpdate(); //executa o comando INSERT
            
            JOptionPane.showMessageDialog(null,"Usuário cadastrado.");
            
            //4- limpar os campos após o cadastro
            textUsuario.setText("");
            textSenha.setText("");
            textUsuario.requestFocus();
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte. ERRO: "+ex.getMessage());
        } catch (SQLException ex) {
            String erro = ex.getMessage();
            if (erro.contains("Duplicate entry")){
                JOptionPane.showMessageDialog(null,"Usuário já cadastrado.");
            }
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte. ERRO: "+ex.getMessage());
        }
    }//GEN-LAST:event_buttonSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JComboBox<String> comboBoxCargo;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTextField textSenha;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
