/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author enzo.gpelizaro
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CadastrarFuncionario extends javax.swing.JFrame {

    Connection conex = ConexaoBdMenu.conectar();

    /**
     * Creates new form CadastrarProdutos
     */
    public CadastrarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textTelefoneFuncionario = new javax.swing.JTextField();
        textIdFuncionario = new javax.swing.JTextField();
        textNomeFuncionario = new javax.swing.JTextField();
        buttonCadastrarFuncionario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textEmailFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textEnderecoFuncionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textBairroFuncionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textCidadeFuncionario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textEstadoFuncionario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Tefefone:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 160, 170, 60);

        jLabel2.setText("ID funcionario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 170, 60);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 170, 60);
        getContentPane().add(textTelefoneFuncionario);
        textTelefoneFuncionario.setBounds(130, 170, 250, 40);

        textIdFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(textIdFuncionario);
        textIdFuncionario.setBounds(130, 30, 250, 40);
        getContentPane().add(textNomeFuncionario);
        textNomeFuncionario.setBounds(130, 100, 250, 40);

        buttonCadastrarFuncionario.setText("Cadastrar");
        buttonCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCadastrarFuncionario);
        buttonCadastrarFuncionario.setBounds(320, 330, 180, 40);

        jLabel5.setText("Email:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 170, 60);
        getContentPane().add(textEmailFuncionario);
        textEmailFuncionario.setBounds(130, 240, 250, 40);

        jLabel6.setText("Endereço:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 20, 170, 60);
        getContentPane().add(textEnderecoFuncionario);
        textEnderecoFuncionario.setBounds(530, 30, 250, 40);

        jLabel7.setText("Bairro:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 90, 170, 60);
        getContentPane().add(textBairroFuncionario);
        textBairroFuncionario.setBounds(530, 100, 250, 40);

        jLabel8.setText("Cidade:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 160, 170, 60);
        getContentPane().add(textCidadeFuncionario);
        textCidadeFuncionario.setBounds(530, 170, 250, 40);

        jLabel9.setText("Estado:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 220, 170, 60);
        getContentPane().add(textEstadoFuncionario);
        textEstadoFuncionario.setBounds(530, 230, 250, 40);

        setSize(new java.awt.Dimension(841, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textIdFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIdFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIdFuncionarioActionPerformed

    private void buttonCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarFuncionarioActionPerformed
        try {
            String id, nome, endereco, bairro, cidade, estado, telefone, email;
            id = textIdFuncionario.getText();
            nome = textNomeFuncionario.getText();
            endereco = textEnderecoFuncionario.getText();
            bairro = textBairroFuncionario.getText();
            cidade = textCidadeFuncionario.getText();
            estado = textEstadoFuncionario.getText();
            telefone = textTelefoneFuncionario.getText();
            email = textEmailFuncionario.getText();
            
            if (id.equals("") || nome.equals("") || endereco.equals("") || bairro.equals("")||cidade.equals("")||estado.equals("")||telefone.equals("")||email.equals("")) {
                JOptionPane.showMessageDialog(null, "Insira todas as informações: ");
            } else {
                PreparedStatement st = conex.prepareStatement("INSERT INTO funcionario values (?,?,?,?,?,?,?,?)");
                st.setString(1, id);
                st.setString(2, nome);
                st.setString(3, endereco);
                st.setString(4, bairro);
                st.setString(5, cidade);
                st.setString(6, estado);
                st.setString(7, telefone);
                st.setString(8, email);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Funcionario cadastrado.");
                textIdFuncionario.setText("");
                textNomeFuncionario.setText("");
                textEnderecoFuncionario.setText("");
                textBairroFuncionario.setText("");
                textCidadeFuncionario.setText("");
                textEstadoFuncionario.setText("");
                textTelefoneFuncionario.setText("");
                textEmailFuncionario.setText("");
                textIdFuncionario.requestFocus();
            }

        } catch (SQLException ex) {
            Logger.getLogger(CadastrarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonCadastrarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textBairroFuncionario;
    private javax.swing.JTextField textCidadeFuncionario;
    private javax.swing.JTextField textEmailFuncionario;
    private javax.swing.JTextField textEnderecoFuncionario;
    private javax.swing.JTextField textEstadoFuncionario;
    private javax.swing.JTextField textIdFuncionario;
    private javax.swing.JTextField textNomeFuncionario;
    private javax.swing.JTextField textTelefoneFuncionario;
    // End of variables declaration//GEN-END:variables
}
