
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enzo.gpelizaro
 */
public class ListarFuncionario extends javax.swing.JFrame {

    static String idTabela, nomeTabela, enderecoTabela, bairroTabela, cidadeTabela, estadoTabela, telefoneTabela, emailTabela;
    static PreparedStatement st;
    static ResultSet rs;
    static DefaultTableModel modefi;
    Connection conex = ConexaoBdMenu.conectar();

    /**
     * Creates new form ListarFuncionario
     */
    public ListarFuncionario() {
        initComponents();
        listarFuncionarios();
    }

    private void listarFuncionarios() {
        try {
            st = conex.prepareStatement("SELECT * FROM funcionario;");
            rs = st.executeQuery();
            DefaultTableModel tblModelo = (DefaultTableModel) tableFuncionario.getModel();
            tblModelo.setRowCount(0);
            while (rs.next()) {
                String linha[] = {
                    idTabela = rs.getString("id"),
                    nomeTabela = rs.getString("nome"),
                    enderecoTabela = rs.getString("endereco"),
                    bairroTabela = rs.getString("bairro"),
                    cidadeTabela = rs.getString("cidade"),
                    estadoTabela = rs.getString("estado"),
                    telefoneTabela = rs.getString("telefone"),
                    emailTabela = rs.getString("email")
                };
                tblModelo.addRow(linha);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ListarFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableFuncionario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Endereço", "Bairro", "Cidade", "Estado", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableFuncionario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(66, 90, 620, 406);

        jLabel1.setText("Funcionários");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 30, 90, 30);

        setSize(new java.awt.Dimension(789, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFuncionario;
    // End of variables declaration//GEN-END:variables
}
